# "$schema" = 'https://starship.rs/config-schema.json'
# add_newline = false
# format = """
# [╭](#d8dee9) [](#b48ead)[](fg:#000000 bg:#b48ead)[ ](#b48ead)$username$directory$all$line_break$character"""
#
# right_format = """$git_branch$git_state$git_status$time"""
#
# # welcome, this is NOT entirely my orginial work. i don't remember who i got it from, so if this is yours, and you want credit added, email me @ ri@bersyon.org with proof that its yours.
#
#
# # the OS section is kinda disabled by default. to enable it, add '$os' to the bracket where the ◈ is. 
# # otherwise, set it to whatever you want.
#
# [os]
# format = "$symbol"
# disabled = true
#
# [os.symbols]
# Alpine = ''
# Amazon = ''
# Android = ''
# Arch = '󰣇'
# CentOS = ''
# Debian = ''
# EndeavourOS = ''
# Fedora = ''
# FreeBSD = ''
# Garuda = ''
# Gentoo = ''
# Linux = ''
# Macos = ''
# Manjaro = ''
# Mariner = ''
# Mint = ''
# NetBSD = ''
# NixOS = ''
# OpenBSD = ''
# OpenCloudOS = ''
# openEuler = ''
# openSUSE = ''
# OracleLinux = '⊂⊃'
# Pop = ''
# Raspbian = ''
# Redhat = ''
# RedHatEnterprise = ''
# Solus = ''
# SUSE = ''
# Ubuntu = ''
# Unknown = ''
# Windows = ''
#
# [character]
# success_symbol = "[╰─❯](#ffffff)"
# error_symbol = "[╰─×](#ff0000)"
#
# [git_branch]
# format = "[ $symbol $branch ]($style) "
# symbol = ""
# style = "#00ff00"
#
# [directory]
# format = "[](#b48ead)[$path]($style)[ ](#b48ead)"
# style = "fg:#ffffff bg:#b48ead"
# truncate_to_repo=false
#
# [username]
# style_user = "#b48ead"
# show_always = true
#
# [time]
# format = "[$time](#b48ead)"
# time_format = "%a, %H:%M"
# disabled = false
#
# [python]
# disabled = true

add_newline = false

[username]
style_user = "cyan bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = 'on [$hostname](bold purple) '
trim_at = "."
disabled = false

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[](bold cyan)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[](bold red)"

[directory]
read_only = " "
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold italic blue"

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold italic red"

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

#[directory]
#read_only = " "

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[haskell]
symbol = "λ "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = " "

[nodejs]
format = "via [ Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

# add_newline = false
# command_timeout = 200
# format = "[$directory$git_branch$git_status]($style)$character"
#
# [character]
# error_symbol = "[✗](bold cyan)"
# success_symbol = "[❯](bold cyan)"
#
# [directory]
# truncation_length = 2
# truncation_symbol = "…/"
# repo_root_style = "bold cyan"
# repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
#
# [git_branch]
# format = "[$branch]($style) "
# style = "italic cyan"
#
# [git_status]
# format     = '[$all_status]($style)'
# style      = "cyan"
# ahead      = "⇡${count} "
# diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
# behind     = "⇣${count} "
# conflicted = " "
# up_to_date = " "
# untracked  = "? "
# modified   = " "
# stashed    = ""
# staged     = ""
# renamed    = ""
# deleted    = ""
